[book]
title = "Sit With Ariadne"
description = "Meditation and peer-support things."
authors = ["Ariadne"]
language = "en"

[output.html]
git-repository-url = "https://github.com/sitwithariadne/website"
